language: node_js
node_js:
    - "12"
branches:
    only:
        - master
        - develop

addons:
    sonarcloud:
        organization: "usdot-jpo-sdc"

before_script:
  - npm install -g @angular/cli

script:
    - cd webportal/webapp && npm test-headless
    - sonar-scanner -X -D sonar.login=$SONAR_TOKEN
