matrix:
  include:
    - language: node_js
      node_js: "12"
      branches:
        - only:
          - master
          - develop
      addons:
        - sonarcloud:
          - organization: "usdot-jpo-sdc"
      before_script:
        - npm install -g @angular/cli
      env:
        - TEST_DIR=webportal/webapp/
      script:
        - cd $TEST_DIR && npm install && npm run test-headless
        - cd ../../ && sonar-scanner -X -D sonar.login=$SONAR_TOKEN
    - langauge: python
      python: 3.6
      branches:
        - only:
          - master
          - develop
      addons:
        - sonarcloud:
          - organization: "usdot-jpo-sdc"
      install:
        - . ./webportal/lambda/setup_venv.sh
      env:
        - TEST_DIR=webportal/lambda/
      script:
        - cd $TEST_DIR && coverage run -m pytest
        - cd ../../ && sonar-scanner -X -D sonar.login=$SONAR_TOKEN