language: node_js
node_js:
    - "12"
branches:
    only:
        - master
        - develop

addons:
    sonarcloud:
        organization: "usdot-jpo-sdc"

before_script:
  - npm install -g @angular/cli

script:
    - ng test --watch=false --browsers=ChromeHeadless
    - sonar-scanner -X -D sonar.login=$SONAR_TOKEN
