language: node_js
node_js:
    - "12"
branches:
    only:
        - master
        - develop

addons:
    sonarcloud:
        organization: "usdot-jpo-sdc"

before_script:
  - npm install -g @angular/cli

env:
  - TEST_DIR=webportal/webapp/

script:
    - cd $TEST_DIR && npm test-headless
    - sonar-scanner -X -D sonar.login=$SONAR_TOKEN
